library(DescTools)
data <- read.csv("/Users/macintoshhd/Desktop/Homework/Statistics/Homework4/ch8/exercise8_5.csv",header = TRUE, fileEncoding = "GBK")
attach(data)
model_1w <- aov(行车时间~时段)
summary(model_1w)
model_2w <- aov(行车时间~路段)
summary(model_1w)
model_Bw <- aov(行车时间~时段+路段+时段:路段)
summary(model_Bw)
EtaSq(model_Bw, anova = T)