library(DescTools)
data <- read.csv("/Users/macintoshhd/Desktop/Homework/Statistics/Homework4/ch8/exercise8_6.csv",header = TRUE, fileEncoding = "GBK")
attach(data)
model_1w <- aov(销售量~广告方案)
summary(model_1w)
model_2w <- aov(销售量~广告媒体)
summary(model_2w)
model_Bw <- aov(销售量~广告方案+广告媒体+广告方案:广告媒体)
summary(model_Bw)
EtaSq(model_Bw, anova = T)